# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20170213_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='hand_up_date_time',
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submit_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Submit Date and Time'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='submit_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Deadline Date and Time'),
        ),
    ]
