# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20170213_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='submit_date_time',
            new_name='required_submit_date_time',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='questionnaire_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='study_director_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='study_id',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='max_show_up_times_per_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='proband_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Proband'),
        ),
    ]
