# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20170213_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydirector',
            name='mail_address',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False, verbose_name=b'Email-Address'),
        ),
    ]
