# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20170213_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='end_date_time',
            field=models.DateTimeField(verbose_name=b'End Date and Time'),
        ),
        migrations.AlterField(
            model_name='study',
            name='start_date_time',
            field=models.DateTimeField(verbose_name=b'Start Date and Time'),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_director_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.StudyDirector'),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_name',
            field=models.CharField(max_length=30, verbose_name=b'Study Name'),
        ),
        migrations.AlterField(
            model_name='studydirector',
            name='_passwort',
            field=models.CharField(max_length=20, verbose_name=b'Passwort'),
        ),
        migrations.AlterField(
            model_name='studydirector',
            name='titel',
            field=models.CharField(max_length=20, verbose_name=b'Titel'),
        ),
    ]
