# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20170213_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice_value',
            field=models.CharField(max_length=30, verbose_name=b'Answer of Choice Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='integer_value',
            field=models.FloatField(verbose_name=b'Answer of Scale Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='proband_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Proband'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.IntegerField(null=True, verbose_name=b'Question ID'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_type',
            field=models.CharField(max_length=30, verbose_name=b'Question Type'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='submit_date_time',
            field=models.DateTimeField(null=True, verbose_name=b'Submit Date and Time'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='option',
            field=models.TextField(verbose_name=b'Option'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='question_content',
            field=models.TextField(verbose_name=b'Question Content'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='question_type',
            field=models.CharField(max_length=30, verbose_name=b'Question Type'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='questionnaire_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='study_director_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.StudyDirector'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='study_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Study'),
        ),
        migrations.AlterField(
            model_name='notansweredquestionnaire',
            name='proband_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Proband'),
        ),
        migrations.AlterField(
            model_name='notansweredquestionnaire',
            name='questionnaire_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='integer_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='personal_information_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='proband_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Proband'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='string_value',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='proband',
            name='study_director_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.StudyDirector'),
        ),
        migrations.AlterField(
            model_name='proband',
            name='study_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Study'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='max_show_up_times_per_day',
            field=models.IntegerField(null=True, verbose_name=b'Max Show Up Times Per Day'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire_name',
            field=models.CharField(max_length=30, verbose_name=b'Questionnaire Name'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='required_submit_date_time',
            field=models.DateTimeField(null=True, verbose_name=b'Deadline Date and Time'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='study_director_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.StudyDirector'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='study_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Study'),
        ),
        migrations.AlterField(
            model_name='scalequestion',
            name='gap_value',
            field=models.FloatField(verbose_name=b'Gap'),
        ),
        migrations.AlterField(
            model_name='scalequestion',
            name='max_value',
            field=models.FloatField(verbose_name=b'Maximum'),
        ),
        migrations.AlterField(
            model_name='scalequestion',
            name='min_value',
            field=models.FloatField(verbose_name=b'Minimum'),
        ),
        migrations.AlterField(
            model_name='scalequestion',
            name='question_content',
            field=models.TextField(verbose_name=b'Question Content'),
        ),
        migrations.AlterField(
            model_name='scalequestion',
            name='question_type',
            field=models.CharField(max_length=30, verbose_name=b'Question Type'),
        ),
        migrations.AlterField(
            model_name='scalequestion',
            name='questionnaire_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='scalequestion',
            name='study_director_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.StudyDirector'),
        ),
        migrations.AlterField(
            model_name='scalequestion',
            name='study_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Study'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='question_content',
            field=models.TextField(verbose_name=b'Question Content'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='question_type',
            field=models.CharField(max_length=30, verbose_name=b'Question Type'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='questionnaire_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='study_director_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.StudyDirector'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='study_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Study'),
        ),
        migrations.AlterField(
            model_name='triggerevent',
            name='name',
            field=models.CharField(choices=[(b'Acc', b'Accelerometer'), (b'Li_Acc', b'Linear Acceleration'), (b'Grav', b'Gravity'), (b'Rota', b'Rotation Vector'), (b'Tem', b'Temperature'), (b'Light', b'Light'), (b'Pres', b'Pressure'), (b'Hum', b'Relative Humidity'), (b'Mag', b'Magnetic Field'), (b'Prox', b'Proximity')], max_length=10, verbose_name=b'Trigger Event Name'),
        ),
        migrations.AlterField(
            model_name='triggerevent',
            name='questionnaire_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='triggerevent',
            name='value',
            field=models.CharField(max_length=30, verbose_name=b'Value'),
        ),
    ]
